name: Monthly Fun Fact Update

on:
  schedule:
    - cron: '0 8 1 * *'  # Tous les 1ers du mois à 08:00 UTC
  workflow_dispatch:     # Pour pouvoir aussi le lancer manuellement

jobs:
  update-fun-fact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Run fun fact updater
        run: python update_fun_facts.py

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "🔁 Update Fun Fact of the Month"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_PUSH_OPTIONS: --force-with-lease
          GIT_PUSH_URL: https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          GIT_BRANCH: main  # Changez cela si votre branche principale est différente
