name: Monthly Fun Fact Update

on:
  schedule:
    - cron: '0 8 1 * *'  # Tous les 1ers du mois à 08:00 UTC
  workflow_dispatch:     # Pour pouvoir aussi le lancer manuellement

jobs:
  update-fun-fact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9 

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Run fun fact updater
        run: python update_fun_facts.py

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
      - name: Pull latest changes before commit
        run: git pull --rebase

      - name: Commit and push if README has changed
        run: |
          if ! git diff --quiet README.md; then
            git add README.md
            git commit -m "🔁 Update Fun Fact of the Month"
            git push
          else
            echo "✅ No changes to commit."
          fi

